"""The order's chronicle: Nicholas Glassberger, Chronica, on the years 1322-1329,
from Analecta Franciscana II (Quaracchi: Collegium S. Bonaventurae, 1887),
pp. 129-133, 140, 145-146.

Internet Archive analectafrancisc02coll (printed page n = leaf n+39). The OCR
was read against every page image. The editors' text is kept as printed, with
their italics dropped; their footnotes are used in the notes. Glassberger, a
Franciscan of the Observance in Nuremberg, wrote c. 1491-1508 and copied, for
these years, the Chronica XXIV Generalium of the fourteenth century, whose own
edition (Analecta Franciscana III, 1897) is not on the Internet Archive; the
Quaracchi editors mark the parallels. Cuts are marked […].
English: the site's working translation (CC0).

Each unit: pg (Analecta page), titel, orig, en, note."""

PERUGIA = [
 {"pg": "129",
  "titel": "The question at Perugia",
  "orig": "Anno Domini 1322 in festo Pentecostes fuit Perusii celebratum capitulum generale, in quo capitulo fuit praedicta quaestio de paupertate Christi, quae in Curia domini Papae ventilabatur, per patres capituli determinata, et de hoc litterae talis tenoris factae: Universis Christifidelibus praesentes litteras inspecturis, fratres Michael, Ordinis Fratrum Minorum Generalis Minister, Gulielmus Angliae, Henricus Superioris Alamanniae, Arnaldus Aquitaniae, Provinciales Ministri et in sacra theologia magistri; nec non Hugo de Novo Castro et Gulielmus de Almuchia, sacrae theologiae doctores; Nicolaus, Minister Franciae, et Gulielmus Block, baccalaurei in sacra Pagina, et omnes Ministri et Custodes, Discreti et Lectores generalium studiorum, apud Perusium congregati in capitulo generali, ipsumque totum generale capitulum Ordinis supradicti salutem et pacem in Domino sempiternam. Noveritis, quod nos anno Domini 1322, indictione V, pridie nonas Iunii, audita et intellecta quaestione quadam, quae in Curia Romana principaliter agitatur, qua quaeritur, utrum asserere, Christum et Apostolos non habuisse aliquid in speciali nec in communi, sit haereticum; et requisiti, quid de ipsa quaestione sentiremus, et in scriptis sub nostris sigillis et subscriptionibus propriis redigere curaremus:",
  "en": "In the year of the Lord 1322, on the feast of Pentecost, the general chapter was held at Perugia; in which chapter the said question of the poverty of Christ, which was being argued in the lord pope's curia, was determined by the fathers of the chapter, and letters of the following tenor were made about it: To all the faithful of Christ who shall see the present letters, brothers Michael, general minister of the order of Friars Minor; William of England, Henry of Upper Germany, Arnold of Aquitaine, provincial ministers and masters in sacred theology; and also Hugh of Newcastle and William of Alnwick, doctors of sacred theology; Nicholas, minister of France, and William Bloc, bachelors of the sacred page; and all the ministers and custodians, discreets and lectors of the general houses of study, gathered at Perugia in general chapter, and the whole general chapter of the said order: greeting and everlasting peace in the Lord. Know that we, in the year of the Lord 1322, fifth indiction, on the day before the Nones of June, having heard and understood a certain question which is chiefly being argued in the Roman curia, in which it is asked whether to assert that Christ and the apostles had nothing individually nor in common is heretical; and having been asked what we think on this question, and to set it down in writing under our seals and our own signatures:",
  "note": "4 June 1322 (Pentecost fell on 30 May). The letter is also printed by Wadding, Annales Minorum, 1322 n. LII, and in Baluze's Miscellanea ed. Mansi III, p. 208, whose variants the editors give. William of Alnwick was one of the most eminent Franciscan theologians of the day. The 'question argued in the curia' is the one the pope had opened in March (Decr. Nonnunquam [3])."},
 {"pg": "130",
  "titel": "'Not heretical, but sound, catholic and faithful'",
  "orig": "visis et examinatis dicta quaestione cum allegationibus, quae pro et contra fiunt, diligentique et matura deliberatione digestis, determinationi sanctae Romanae Ecclesiae firmiter et totaliter inhaerentes, concorditer et unanimiter dicimus et fatemur, quod dicere et asserere, quod Christus viam perfectionis ostendens, et Apostoli eandem viam perfectionis sequentes atque per exemplum in alios, volentes perfecte vivere, derivantes, nihil iuris proprietatis et dominii seu iuris proprii in speciali et in communi habuerunt, non est haereticum, sed sanum, catholicum et fidele, maxime cum sancta Romana Ecclesia catholica, quae a tramite Apostolicae traditionis nunquam deviasse, aut errasse probatur, (Causa) XXIV. q. 1: A recta, et cap.: Pudenda, in fine, hoc expresse dicat, affirmet et determinet manifeste, Extravag. de verborum significatione, in capitulo: Exiit, libro VI. § Porro, sic inquiens: « Dicimus, quod abdicatio proprietatis omnium rerum tam in speciali quam etiam in communi propter Deum meritoria est et sancta, quam et Christus, viam perfectionis ostendens, verbo docuit et exemplo firmavit, quamque primi fundatores militantis Ecclesiae, id est Apostoli, prout ab ipso fonte, id est Christo, hauserant, in volentes perfecte vivere per doctrinae ac vitae ipsorum alveos derivaverunt ». Quae Ecclesiae determinatio libro VI. per ipsam catholicam Ecclesiam est inserta, et per aliam Decretalem in Viennensi concilio promulgatam, et est in VII. libro sub titulo: de verborum significatione inserta, et per ipsam universalem et catholicam Ecclesiam est approbata, ac novissime per sanctissimum patrem et dominum, dominum Iohannem, divina providentia Papam XXII, in quadam sua declaratione, edita super regulam et statum Fratrum Minorum, quae incipit: Quorundam exigit etc., est eadem declaratio plurimum commendata tamquam salubriter edita, solida, lucida multaque maturitate digesta.",
  "en": "having seen and examined the question with the arguments made for and against, and digested them with diligent and mature deliberation, holding firmly and wholly to the determination of the holy Roman Church, we say and confess in concord and unanimously that to say and assert that Christ, showing the way of perfection, and the apostles, following the same way of perfection and passing it on by example to others who wish to live perfectly, had nothing by right of property and ownership, or of right of their own (nihil iuris proprietatis et dominii seu iuris proprii), individually and in common, is not heretical, but sound, catholic and faithful; above all since the holy catholic Roman Church, which is proved never to have strayed or erred from the path of apostolic tradition (Causa 24, q. 1, A recta, and the chapter Pudenda at the end), expressly says, affirms and plainly determines it in the Extravagant On the meaning of words, in the chapter Exiit, book VI, § Porro, saying: 'We say that the renunciation of ownership of all things, both individually and in common, for God's sake, is meritorious and holy; which Christ, showing the way of perfection, taught by word and confirmed by example, and which the first founders of the Church militant, that is the apostles, as they had drawn it from that very spring, that is Christ, passed on through the channels of their teaching and life to those who wish to live perfectly.' Which determination of the Church was put into book VI by the catholic Church itself, and by another decretal promulgated at the Council of Vienne, and put into book VII under the title On the meaning of words, and approved by the universal and catholic Church itself; and most recently the same declaration was highly commended by the most holy father and lord, lord John XXII, by divine providence pope, in a declaration of his on the rule and state of the Friars Minor beginning Quorundam exigit, as soundly issued, solid, lucid and digested with much deliberation.",
  "note": "The chapter quotes Exiit § Porro (Exiit [2]) with the glosses 'that is the apostles', 'that is Christ', and turns John XXII's own praise of his predecessors' declarations in Quorundam exigit (Decr. Exigit [1]) against him. Its formula, 'nothing by right of property and ownership … individually and in common', is what the pope declared heretical seventeen months later (Decr. Nonnullos [1]). Wadding and Mansi read 'iure proprietatis' for 'iuris proprietatis'."},
 {"pg": "130–131",
  "titel": "Sealed, and a longer determination",
  "orig": "Et testante Canone, XIX. distinctione, cap.: Si Romanorum, illud quod pro sano dogmate Sedes Apostolica approbavit, semper teneri debet acceptum, nec ab eo licet alicui quomodolibet resilire, (Causa) XXIV. q. 1: Haec est fides. In huius autem nostrae opinionis et communis ac concordis sententiae testimonium et munimen praesentem seriem de communi consensu omnium nostrum sub sigillis et subscriptionibus propriis Generalis Ministri et nominatorum superius magistrorum ac baccalaureorum in sacra Pagina, nec non et quatuor Provincialium Ministrorum, videlicet Thomae Provinciae Bononiensis, Petri Provinciae sancti Francisci, Ferdinandi Provinciae Castellae et Simonis Provinciae Thuroniae, duximus muniendam. Datum Perusii, anno et mense et die superius memoratis. Item, ultra praedictam litteram definitivam fecerunt dicti Generalis et Provinciales Ministri ac baccalaurei, in dicto capitulo existentes, de dicta quaestione aliam determinationem et definitionem magis diffusam, iuribus et rationibus confirmatam, quam ponit Alvarus, de Planctu Ecclesiae in II. parte, articulo LXII, vide ibidem. Super qua determinatione fuit dominus Papa non modicum indignatus.",
  "en": "And as the canon testifies (Distinction 19, chapter Si Romanorum), what the apostolic see has approved as sound doctrine must always be held as accepted, and no one may in any way draw back from it (Causa 24, q. 1, Haec est fides). In witness and confirmation of this our opinion and common and concordant judgement, we have had the present text fortified, by the common consent of all of us, with the seals and signatures of the general minister and of the masters and bachelors of the sacred page named above, and also of four provincial ministers, namely Thomas of the province of Bologna, Peter of the province of Saint Francis, Ferdinand of the province of Castile and Simon of the province of Touraine. Given at Perugia, in the year, month and day recorded above. Moreover, beyond this definitive letter, the said general and provincial ministers and bachelors present at the chapter made another determination and definition of the question, more extensive and confirmed by laws and reasons, which Alvarus gives in The Lament of the Church, part II, article 62; see there. At this determination the lord pope was not a little angered.",
  "note": "The canon 'what the apostolic see has approved … must always be held' is the argument the friars developed into the 'key of knowledge' (Decr. Quorundam [2]). Alvarus Pelagius, a Franciscan at the curia, copied the longer Perugia text into his De planctu ecclesiae (1330s); its sixteenth-century printings are the next place to look for it."},
 {"pg": "131",
  "titel": "Michael before the pope",
  "orig": "Praeterea, dictus Minister Generalis ad praesentiam domini Papae se conferens et dictam sui capituli determinationem defendens, non habuit se ita reverenter et prudenter, sicut debuit. Quare motum Pontificem Summum magis irritavit; in quo magnam Ordini tribulationem suscitavit, qualis antea non legitur. Et fallacibus aliquibus susurronibus et detractoribus indignationem domini Papae contra Religionem succendentibus, irreparabile malum Ordini suscitatur. […] Praedictam determinationem capituli generalis omnes magistri et baccalaurei in sacra Pagina de Ordine Parisius et in Anglia commorantes, numero quadraginta unus, approbaverunt, et de hoc fecerunt patentes litteras, eorum sigillis et subscriptionibus roboratas. Papa autem hoc audiens, iratus, suggestione quorundam de Ordine Praedicatorum, edidit Constitutionem: Ad conditorem canonum etc.",
  "en": "Moreover, the said general minister, going into the lord pope's presence and defending his chapter's determination, did not bear himself as reverently and prudently as he ought. For this he provoked the supreme pontiff, already moved, still further; and in this he raised a great tribulation for the order, such as is not read of before. And with some deceitful whisperers and detractors kindling the lord pope's anger against the religion, an irreparable evil is raised for the order. […] All the masters and bachelors of the sacred page of the order living at Paris and in England, forty-one in number, approved the general chapter's determination, and made letters patent about it, strengthened with their seals and signatures. But the pope, hearing this, in anger, at the suggestion of some of the order of Preachers, issued the constitution Ad conditorem canonum.",
  "note": "The chronicle, written in an order that had submitted, blames its own general for want of reverence and the Dominicans for the pope's anger. The cut records the provincial chapter of Basel of 1322, which ordered masses and prayers in every house 'for our tribulation'. On Ad conditorem see Decr. Conditorem [1]–[12]."},
]

APPEAL = [
 {"pg": "132–133",
  "titel": "Bonagratia's appeal, and the dark prison",
  "orig": "Hac igitur Constitutione a domino Iohanne Papa edita et solemniter promulgata, et elapso spatio triginta octo dierum ab ipsa publicatione, Anno Domini 1323 frater Bonagratia de Bergamo, doctor utriusque iuris, procurator Ordinis Minorum in Curia Romana, ad hoc specialiter institutus, ab ipsa Constitutione et in ea contentis provocavit et appellavit, et publice protestatus est, porrecto libello, qui incipit: In nomine Domini. Amen. Anno a nativitate Domini MCCCXXIII, indictione VI, die XIV. mensis Ianuarii, in civitate Avenionensi in palatio sanctissimi patris et domini, domini Iohannis, divina providentia Papae XXII, in consistorio Cardinalium, more solito congregato et convocato, ibi frater Bonagratia de Bergamo, procurator, et procuratorio nomine Ordinis Fratrum Minorum in praesentia praefati domini Papae et Collegii dominorum Cardinalium ibidem ad consistorium congregatorum personaliter constitutus, publice dedit ac porrexit et praesentavit praefato domino Papae, sive domino Bertrando de Monte Faventis Cardinali, ibi praesenti et de mandato ipsius domini Papae recipienti infrascriptum libellum provocationis et appellationis sive supplicationis […]. In qua appellatione, ad sanctam Romanam Ecclesiam et Sedem Apostolicam facta, frater Bonagratia ostendere nisus est, dictam Constitutionem sacrae Scripturae et fidei catholicae obviare. Quamobrem fecit eum dominus Papa Iohannes statim de facto, omni audientia ei denegata, atro carceri mancipari, in quo detinuit eum per annum minus viginti diebus, et pro tunc nihil ad appellationem respondit.",
  "en": "When this constitution had been issued and solemnly promulgated by the lord Pope John, and thirty-eight days had passed since its publication, in the year of the Lord 1323 brother Bonagratia of Bergamo, doctor of both laws, procurator of the order of Minors in the Roman curia, specially appointed for this, appealed and protested publicly against the constitution and its contents, presenting a document which begins: In the name of the Lord, amen. In the year from the Nativity of the Lord 1323, sixth indiction, on the fourteenth day of January, in the city of Avignon, in the palace of the most holy father and lord, lord John XXII, by divine providence pope, in the consistory of the cardinals gathered and convoked in the usual way, brother Bonagratia of Bergamo, procurator, and in the name of procurator of the order of Friars Minor, appearing in person before the said lord pope and the college of lord cardinals gathered there for the consistory, publicly gave, handed and presented to the lord pope, or to lord Bertrand de Montfavès, cardinal, present there and receiving it by the lord pope's command, the document of provocation and appeal or supplication written below […]. In this appeal, made to the holy Roman Church and the apostolic see, brother Bonagratia tried to show that the said constitution was contrary to sacred scripture and the catholic faith. For which the lord Pope John at once, in fact, denying him any hearing, had him thrown into a dark prison, in which he held him for a year less twenty days, and for the time made no answer to the appeal.",
  "note": "14 January 1323. The appeal's full text is in Baluze's Miscellanea ed. Mansi III, p. 213 (the editors' note). The cut gives its opening, which appeals to Gregory IX's interpretation of the rule. The pope answered by reissuing Ad conditorem in a sharper form."},
 {"pg": "133",
  "titel": "A Dominican saint, and Quum inter nonnullos",
  "orig": "Eodem anno, XV. kalendas Augusti, canonizavit dominus Iohannes XXII. beatum Thomam de Aquino in favorem Fratrum Praedicatorum sibi adhaerentium, ab eius transitu ex hoc mundo anno quinquagesimo. Eodem quoque anno, II. idus Novembris, edidit dominus Iohannes Papa Constitutionem, quae incipit: Cum inter nonnullos etc., in qua dicit, haereticum esse censendum asserere, Christum ac Apostolos nihil habuisse proprii neque in communi neque in speciali. Similiter haereticum dicit affirmare, quod Christo eiusque Apostolis in his, quae eos habuisse sacra Scriptura testatur, nequaquam ius ipsis utendi competierit, nec illa donandi aut ex ipsis alia acquirendi; et, ut dicit Platina in Historia Summorum Pontificum, litteras Constitutionum ad gymnasia publica transmisit, ne amplius Scholastici ea de re disputare auderent. Et dicit Platina, quod certe non multum cum sacra Scriptura convenit, quae multis in locis testatur, Christum eiusque discipulos nihil proprii habuisse, ut illud Evangelii: Qui non vendiderit omnia, quae habet, et pauperibus dederit, non potest meus esse discipulus etc.",
  "en": "The same year, on the fifteenth day before the Kalends of August, the lord John XXII canonized blessed Thomas Aquinas, in favour of the Friars Preachers who adhered to him, in the fiftieth year after his passing from this world. The same year too, on the second day before the Ides of November, the lord Pope John issued the constitution beginning Cum inter nonnullos, in which he says that it is to be judged heretical to assert that Christ and the apostles had nothing of their own, neither in common nor individually. Likewise he says it is heretical to affirm that Christ and his apostles had in no way a right of using the things scripture testifies they had, nor of giving them or of acquiring other things with them; and, as Platina says in his History of the Popes, he sent the letters of the constitutions to the public schools, so that the scholars should no longer dare to dispute on the matter. And Platina says that it certainly does not agree much with sacred scripture, which testifies in many places that Christ and his disciples had nothing of their own, as in that saying of the Gospel: 'Whoever does not sell all that he has and give to the poor cannot be my disciple.'",
  "note": "18 July 1323; 12 November 1323. The chronicler, writing after 1490, cites the humanist Bartolomeo Platina's Lives of the Popes (1479) for a judgement a Franciscan could not safely make in his own voice. The Gospel saying he quotes is a conflation of Luke 14:33 and Luke 18:22 (the editors cite Luke 14:33). On the decretal see Decr. Nonnullos [1]–[2]."},
]

FLIGHT = [
 {"pg": "140",
  "titel": "The galley, and the flight by night",
  "orig": "Eodem anno 1327 Ludovicus, dux Bavariae, Romanorum rex electus, Romae praeter Iohannis Pontificis voluntatem a Sciarra Columnensi, nulla solita solemnitate servata, coronatus, sua sententia Iohannem Pontificem privat et Petrum Corbariensem Ordinis Minorum pontificem facit, a quo iterum sibi imponi coronam iubet, et sibi invicem falsi suae dignitatis auctores fiunt. Quibus auditis, Michael de Caesena Avenione existens rogat Ludovicum, galeam sibi mitti; quo facto, 13 die Aprilis in conventu Fratrum Minorum appellavit contra dominum Iohannem Papam ad sanctam catholicam Ecclesiam et protestatus est coram multis et coram magistro Gulielmo Ockam de Anglia et magistro Francisco Rubei de Pignano et magistro Bonagratia de Bergamo, utriusque iuris perito, et multis aliis, et relicta ibi appellatione, nocturno tempore de civitate Avenionensi latenter recessit cum praedictis magistris et ivit ad imperatorem Ludovicum.",
  "en": "The same year 1327 Louis, duke of Bavaria, elected king of the Romans, was crowned at Rome against the will of Pope John by Sciarra Colonna, without any of the customary solemnity; by his own sentence he deprived Pope John and made Pietro of Corvaro, of the order of Minors, pope, by whom he had himself crowned again; and they became to each other the false authors of their dignities. Hearing this, Michael of Cesena, being at Avignon, asked Louis to send him a galley; and when this was done, on the thirteenth day of April, in the convent of the Friars Minor, he appealed against the lord Pope John to the holy catholic Church and protested before many, and before master William Ockham of England and master Francis Rubei of Pignan and master Bonagratia of Bergamo, expert in both laws, and many others; and leaving the appeal there, he secretly left the city of Avignon by night with those masters and went to the emperor Louis.",
  "note": "The chronicler counts the year from the Incarnation (25 March), so '1327' here is 1328: Louis was crowned on 17 January 1328 and made Pietro Rainalducci, a Franciscan, antipope as Nicholas V on 12 May (the editors' notes). Michael's secret appeal is dated 13 April 1328; the flight from Avignon was on the night of 26 May 1328, to the galley waiting at Aigues-Mortes. 'Francis Rubei of Pignan' is Francesco d'Ascoli (Francis of Marchia)."},
 {"pg": "145",
  "titel": "Deposed at Bologna",
  "orig": "Anno Domini 1328 fuit Bononiae capitulum generale celebratum, et fuit frater Michael per dominum Papam ab officio depositus, et dominus frater Bertrandus Cardinalis Vicarius Ordinis substitutus, qui iussit, sequenti anno Parisius capitulum generale pro electione Ministri Generalis celebranda congregari, et hoc litteris suis omnibus Ministris et Custodibus denuntiavit. Tunc frater Michael misit etiam litteras per Ordinem universum Ministris et Custodibus, prohibens sub poena excommunicationis, ne quis ad dictum indictum capitulum accederet, vel Iohanni Papae, quem dicebat haereticum, obediret. Sed nihil profecit. […] Dictus etiam frater Michael de Caesena, dicta depositione Papae et Ordinis non obstante, se Ministrum Generalem scripsit et esse contendit etc.",
  "en": "In the year of the Lord 1328 the general chapter was held at Bologna, and brother Michael was deposed from office by the lord pope, and the lord brother Bertrand, cardinal, was substituted as vicar of the order; who ordered the general chapter to be gathered at Paris the next year to elect the general minister, and announced this by his letters to all the ministers and custodians. Then brother Michael too sent letters through the whole order to the ministers and custodians, forbidding under pain of excommunication that anyone go to the chapter so convoked, or obey Pope John, whom he called a heretic. But it availed nothing. […] The said brother Michael of Cesena, notwithstanding his deposition by the pope and the order, styled himself general minister and claimed to be so.",
  "note": "Bertrand de la Tour, a Franciscan cardinal, governed the order as the pope's vicar. 'But it availed nothing': the whole thesis of the order's defeat in four words. The cut records the deposition of the minister of Aquitaine and the annulment of Michael's constitutions in that province."},
 {"pg": "145–146",
  "titel": "Pisa, Munich, 'heresiarch'",
  "orig": "Supradicto anno, videlicet 1328, Pisis publice et solemniter appellavit frater Michael, frater Bonagratia et frater Gulielmus Ockam a sententiis Iohannis Papae XXII. tamquam ab haeretico, ad Ecclesiam universalem in loco tuto congregandam. Et quia Pisani obediebant Ludovico imperatori, affixit ipse Michael appellationem suam cum multis articulis, in quibus Iohannem Papam criminabatur haereticum, ostiis maioris ecclesiae eiusdem civitatis, die XII. Decembris, et ad principes mundi transmisit. Et profectus cum Ludovico iam coronato, venit Monachium, oppidum Bavariae, et ibi mansit cum sociis suis usque ad mortem suam. Iohannes autem Papa declaravit eundem Michaelem fautorem haereticorum et manifestum haereticum, haeresiarcham et schismaticum, et ab omni gradu depositum privilegio denudavit ecclesiastico.",
  "en": "In the same year, 1328, at Pisa, brother Michael, brother Bonagratia and brother William Ockham appealed publicly and solemnly from the sentences of Pope John XXII, as from a heretic, to the universal Church, to be gathered in a safe place. And since the Pisans obeyed the emperor Louis, Michael himself fixed his appeal, with many articles in which he accused Pope John of heresy, to the doors of the cathedral church of that city on the twelfth day of December, and sent it to the princes of the world. And setting out with Louis, now crowned, he came to Munich, a town of Bavaria, and stayed there with his companions until his death. But Pope John declared the same Michael a supporter of heretics and a manifest heretic, a heresiarch and schismatic, and stripped him, deposed from every degree, of ecclesiastical privilege.",
  "note": "12 December 1328, the cathedral of Pisa: the order's general nailed his case against the pope to a church door. The appeal is in Mansi III, pp. 242 and 246 ff. Michael died in Munich on 29 November 1342."},
 {"pg": "146",
  "titel": "Paris 1329: the order submits",
  "orig": "Anno Domini 1329 in mense Iunio, in die Pentecostes, fuit Parisius generale capitulum celebratum, et fuit frater Gerardus Odonis de Provincia Aquitaniae in Generalem Ministrum electus. In quo capitulo fuerunt valentissimi viri, qui de voluntate domini Bertrandi Cardinalis fratrem Michaelem ad tollendas eius cavillationes de novo ab officio absolverunt, definientes cum peritis in omni facultate, dominum Iohannem Papam fore catholicum et bene de paupertate Christi definivisse, et praefatum Michaelem tamquam haereticum iuste fuisse depositum.",
  "en": "In the year of the Lord 1329, in the month of June, on the day of Pentecost, the general chapter was held at Paris, and brother Gerald Odonis of the province of Aquitaine was elected general minister. In this chapter there were most capable men who, by the will of lord Bertrand the cardinal, absolved brother Michael from office anew, to remove his quibbles, defining with experts in every faculty that the lord Pope John was catholic and had defined well on the poverty of Christ, and that the said Michael had been justly deposed as a heretic.",
  "note": "11 June 1329. The printed text has the misprint 'Christri'. Seven years after Perugia, a general chapter of the same order declared that the pope who condemned Perugia's doctrine 'had defined well on the poverty of Christ'. The argument was not lost; the order gave it up."},
]

SECTIONS = [
    {"id": "perugia", "zk": "Chron. Perugia", "titel": "The chapter of Perugia (June 1322)",
     "blurb": "The order's answer to the pope's question: Christ and the apostles had nothing by right of property 'individually and in common', and to say so is 'not heretical, but sound, catholic and faithful'; forty-one masters of Paris and England agree; Michael defends it before the pope 'not as reverently as he ought'.",
     "units": PERUGIA},
    {"id": "appeal", "zk": "Chron. Appeal", "titel": "The procurator's appeal (1323)",
     "blurb": "Bonagratia of Bergamo appeals in consistory against Ad conditorem and spends a year in a dark prison; the pope canonizes Thomas Aquinas and issues Quum inter nonnullos.",
     "units": APPEAL},
    {"id": "flight", "zk": "Chron. Flight", "titel": "The flight and the deposition (1328–1329)",
     "blurb": "A galley from the emperor, an appeal left behind in Avignon, a flight by night with Ockham and Bonagratia; Michael deposed at Bologna, his appeal nailed to the cathedral doors of Pisa, the new general elected at Paris; 'but it availed nothing'.",
     "units": FLIGHT},
]
