"""The old decretals: Nicholas III, Exiit qui seminat (14 August 1279; Sext 5.12.3) and
Clement V, Exivi de paradiso (Council of Vienne, 6 May 1312; Clem. 5.11.1), in excerpts,
from Friedberg, Corpus iuris canonici II (Leipzig 1881), cols. 1109-1121 and 1193-1199.

Read from the photomechanical reprint (Graz 1955, IA BD1141952; column c is on leaf
(c - 1) // 2 + 36). The text was taken from the OCR of the 1959 reprint and read against
the page images excerpt by excerpt; corrections from the page include terra, carnis,
carne, sed, in propriis, ad actus, ad aeterna, quum, donatur, revocandi, iuris, guardiani,
in plerisque, ad usum. Friedberg's footnote marks are dropped; cuts are marked […].
English: the site's working translation (CC0).

Each unit: pg (Friedberg column), titel, orig, en, note."""

EXIIT = [
 {
  "pg": "1109–1110",
  "titel": "He who sows went out to sow",
  "orig": "Exiit, qui seminat, seminare semen suum, de sinu patris in mundum, veste scilicet humanitatis indutus Dei filius Iesus Christus, verbum evangelicum saturus in singulos probos et reprobos, insipientes et ignaros, studiosos et desides, et iuxta Prophetam colonus futurus in terra, semen suum, doctrinam evangelicam, sine delectu dispersit in omnes, qui, omnia tracturus ad se, omnes salvare venerat, qui tandem se ipsum Deo Patri pro salute omnium in redemptionis humanae pretium immolavit. […] Hi sunt illius sanctae regulae professores, quae evangelico fundatur eloquio, vitae Christi roboratur exemplo fundatoris militantis ecclesiae, Apostolorum eius sermonibus actibusque firmatur. Haec est apud Deum et Patrem munda et immaculata religio, quae, descendens a patre luminum, per eius filium exemplariter et verbaliter Apostolis tradita, et deinde per Spiritum sanctum beato Francisco et eum sequentibus inspirata, totius in se quasi continet testimonium Trinitatis.",
  "en": "He who sows went out to sow his seed: Jesus Christ, the Son of God, came out of the Father's bosom into the world, clothed in the garment of humanity, to sow the word of the Gospel in each and all, good and bad, foolish and ignorant, zealous and slothful; and, as the Prophet says, a husbandman on the earth, he scattered his seed, the teaching of the Gospel, without distinction among all, since he, who would draw all things to himself, had come to save all, and at last offered himself to God the Father as the price of human redemption for the salvation of all. […] These are the professors of that holy rule which is founded on the word of the Gospel, strengthened by the example of the life of Christ, the founder of the Church militant, and confirmed by the words and deeds of his apostles. This is the religion pure and immaculate before God the Father which, coming down from the Father of lights, handed on in example and word by his Son to the apostles, and then inspired by the Holy Spirit in blessed Francis and those who follow him, holds within itself, as it were, the testimony of the whole Trinity.",
  "note": "Dated at Soriano in Nicholas III's second year: the text as printed reads the eighteenth day before the Kalends of September (15 August); Friedberg's note cites the bullarium's nineteenth (14 August 1279), the date usually given. The decretal's first words are Luke 8:5. The medieval summary printed before it: 'A very full constitution, declaring almost all the doubts that can arise about the rule of divine Francis; above all whether the Friars Minor, whom they call Cordeliers, are bound as professors of that rule to all the counsels of the Gospel, and whether they may have anything of their own, receive money, and accept legacies left to them; with many other ambiguities most clearly resolved here.' Boniface VIII put it into the Liber Sextus (1298), which gave it the force of general law. Carried here in eight excerpts."
 },
 {
  "pg": "1112",
  "titel": "Neither individually nor in common",
  "orig": "Porro, quum ipsa regula expresse contineat, quod fratres nihil sibi approprient, nec domum, nec locum, nec aliquam rem, sitque declaratum per eundem praedecessorem nostrum Gregorium IX. et nonnullos alios, hoc servare debere tam in speciali quam etiam in communi, quam sic arctam abdicationem venenosis obtrectationibus aliquorum insensata damnaverit astutia : ne fratrum eorundem perfectionis claritas in talium imperitis sermonibus laceretur, dicimus, quod abdicatio proprietatis huiusmodi omnium rerum non tam in speciali, quam etiam in communi propter Deum meritoria est et sancta, quam et Christus, viam perfectionis ostendens, verbo docuit et exemplo firmavit, quamque primi fundatores militantis ecclesiae, prout ab ipso fonte hauserant, volentes perfecte vivere, per doctrinae ac vitae exempla in eos derivarunt.",
  "en": "Moreover, since the rule expressly contains that the friars shall appropriate nothing to themselves, neither house, nor place, nor anything, and it has been declared by our said predecessor Gregory IX and several others that this must be kept both individually and in common (tam in speciali quam etiam in communi), which so strict a renunciation the senseless cunning of some has condemned with poisonous disparagement: lest the brightness of the friars' perfection be torn by the unskilled talk of such men, we say that the renunciation of ownership of all things, not only individually but also in common, for God's sake, is meritorious and holy; and that Christ, showing the way of perfection, taught it by word and confirmed it by example, and the first founders of the Church militant, as they had drawn it from that very spring, passed it on, by the examples of their teaching and their life, to those who wished to live perfectly.",
  "note": "This is the sentence the whole dispute turned on. In 1322 the Franciscan chapter at Perugia repeated it: Christ and the apostles had nothing, individually or in common. In 1323 John XXII declared that assertion heretical (Decr. Nonnullos [1]), and the friars answered that he had condemned what Nicholas III had defined (Decr. Quorundam [2])."
 },
 {
  "pg": "1112–1113",
  "titel": "The purse",
  "orig": "Nec his quisquam putet obsistere, quod interdum dicitur, Christum loculos habuisse. Nam sic Iesus Christus, cuius perfecta sunt opera, in suis actibus viam perfectionis exercuit, quod, interdum infirmorum imperfectionibus condescendens, et viam perfectionis extolleret, et imperfectorum infirmas semitas non damnaret, sic infirmorum personam Christus suscepit in loculis, sic et in nonnullis aliis infirma humanae carnis assumens, (prout evangelica testatur historia,) non tantum carne, sed et mente condescendit infirmis. Sic enim humanam naturam assumpsit, quod in suis operibus perfectus exsistens, in nostris factus humilis, in propriis permansit excelsus. Sic et summae caritatis dignatione ad actus quosdam nostrae imperfectioni conformes inducitur, quod a summae perfectionis rectitudine non curvatur. Egit namque Christus et docuit opera perfectionis, egit etiam infirma, sicut interdum et in fuga patet et loculis: sed utrumque perfecte perfectus exsistens, ut perfectis et imperfectis se viam salutis ostenderet, qui utrosque salvare venerat, qui tandem mori voluit pro utrisque.",
  "en": "Nor let anyone think it stands against this that Christ is sometimes said to have had a purse (loculos). For Jesus Christ, whose works are perfect, so practised the way of perfection in his acts that, sometimes condescending to the imperfections of the weak, he both exalted the way of perfection and did not condemn the weak paths of the imperfect. So Christ took on the person of the weak in the purse; so too in some other things, taking on the weaknesses of human flesh (as the Gospel story testifies), he condescended to the weak not only in the flesh but also in mind. For he so took on human nature that, perfect in his own works, he was made humble in ours, and remained exalted in what was his own. So too, by the condescension of the highest charity, he is led to certain acts conformed to our imperfection without being bent from the rightness of the highest perfection. For Christ did and taught works of perfection; he also did weak things, as appears at times both in his flight and in the purse; but being perfectly perfect in both, so that he might show himself the way of salvation to the perfect and the imperfect, he who had come to save both, and at last willed to die for both.",
  "note": "The purse is the one Judas carried for Jesus and the disciples (John 12:6; 13:29). It was the pope's strongest scriptural argument in the 1320s: Christ and the apostles had something in common, a purse, and so the assertion that they had nothing 'nor even in common' contradicted scripture (Decr. Nonnullos [1]). Nicholas III's answer: condescension to the weak, like the flight into Egypt."
 },
 {
  "pg": "1113",
  "titel": "Property, possession, usufruct, the right of using, the simple use of fact",
  "orig": "Nec quicquam ex his insurgat erroneum, quod taliter propter Deum proprietatem omnium abdicantes, tanquam homicidae sui vel tentatores Dei, vivendi discrimini se committant. Sic enim se ipsos committant divinae providentiae in vivendo, ut viam non contemnant provisionis humanae: quin vel de iis, quae offeruntur libcraliter, vel de iis, quae mendicantur humiliter, vel de iis, quae conquiruntur per laboricium, sustententur; qui triplex vivendi modus in regula providetur expresse. Profecto, si iuxta promissum Salvatoris nunquam deficiet fides ecclesiae: per consequens nec opera misericordiae subtrahentur, ex quo Christi pauperibus omnis ratio diffidentiae cuiuslibet videtur esse sublata. Et quidem, ubi, (quod non est aliquatenus praesumendum,) haec cuncta deficerent, sicut nec ceteris, sic nec ipsis fratribus iure poli in extremae necessitatis articulo ad providendum sustentationi naturae via, omnibus extrema necessitate detentis concessa, praecluditur, quum ab omni lege extrema necessitas sit exempta, nec talem abdicationem proprietatis omnimodae renunciationem usus rerum cuiquam videatur inducere. Nam quum in rebus temporalibus sit considerare praecipuum proprietatem, possessionem, usumfructum, ius utendi, et simplicem facti usum, et ultimo tanquam necessario egeat, licet primis carere possit vita mortalium: nulla prorsus potest esse professio, quae a se usum necessariae sustentationis excludat. Verum condecens fuit ei professioni, quae sponte devovit Christum pauperem in tanta paupertate sectari, omnium abdicare dominium, et rerum sibi concessarum necessario usu fore contentam. Nec per hoc, quod proprietatem usus et rei cuiusque dominium a se abdicasse videtur, simplici usui omnis rei renunciasse convincitur, qui, inquam, usus non iuris, sed facti tantummodo nomen habens, quod facti est tantum, in utendo praebet utentibus nihil iuris, quin immo necessariarum rerum tam ad vitae sustentationem quam ad officiorum sui status exsecutionem, (excepto, quod de pecunia infra subiungitur,) moderatus usus, sed secundum eorum regulam et veritatem omnimodam concessus est fratribus, quibus rebus fratres licite uti possent, durante concedentis licentia, et iuxta id, quod in praesenti serie continetur.",
  "en": "Nor should anything erroneous arise from this, as if those who thus renounce the ownership of all things for God's sake committed themselves to the danger of death, like suicides or tempters of God. For they commit themselves to divine providence in living in such a way as not to despise the way of human provision: they are sustained by what is offered freely, or begged humbly, or earned by work; which threefold way of living the rule expressly provides. Surely, if according to the Saviour's promise the faith of the Church will never fail, neither will the works of mercy be withdrawn; so that every reason for mistrust seems to be taken away from the poor of Christ. And indeed, where (which is not in any way to be presumed) all this failed, the way granted to all who are in extreme necessity to provide for the sustenance of nature is not closed to the friars any more than to others, by the law of heaven, in the moment of extreme necessity, since extreme necessity is exempt from every law; nor does such a renunciation of all ownership seem to bring with it a renunciation of the use of things. For since in temporal things one must consider chiefly property, possession, usufruct, the right of using, and the simple use of fact (proprietatem, possessionem, usumfructum, ius utendi, et simplicem facti usum), and the life of mortals needs the last as necessary, though it can do without the first: there can be no profession at all that excludes from itself the use of necessary sustenance. But it was fitting for that profession, which vowed of its own accord to follow Christ poor in such poverty, to renounce all ownership and be content with the necessary use of the things granted to it. Nor is it shown, because it seems to have renounced the ownership (proprietatem) of use and the lordship (dominium) of every thing, to have renounced the simple use of every thing; which use, I say, having the name not of right but only of fact, since it is only of fact, gives those who use nothing of right in using; on the contrary, the moderate use of necessary things, both for the sustenance of life and for the performance of the duties of their state (except what is added below about money), has been granted to the friars according to their rule and to the whole truth, things which the friars may lawfully use as long as the grantor's licence lasts, and according to what is contained in the present text.",
  "note": "The five degrees are the centre of the Franciscan position and the target of Ad conditorem: John XXII answered, degree by degree, that in things consumed by use none of them can be separated from ownership (Decr. Conditorem [5]–[8]). 'The law of heaven' (ius poli) is natural and divine law as against the law of the market-place (ius fori)."
 },
 {
  "pg": "1113",
  "titel": "The civil law answered",
  "orig": "Nec his obviare dignoscitur, quod civilis providentia in humanis rebus humane constituit, videlicet non posse usum vel usumfructum a dominio perpetuo separari, quod, ne dominium dominis semper abscedente usu redderetur inutile, temporalem utilitatem tantum in constituendo prospiciens ista decrevit. Retentio namque dominii talium rerum, cum concessione usus facta pauperibus, non est infructuosa domino, quum sit meritoria ad aeterna et professioni pauperum opportuna; quae tanto sibi censetur utilior, quanto commutat temporalia pro aeternis.",
  "en": "Nor is it seen to stand in the way of this that civil provision has humanly established in human affairs that use or usufruct cannot be separated from ownership for ever, which it decreed looking only to temporal advantage in the establishing of it, lest ownership become useless to the owners if the use were always away from them. For the retention of ownership of such things, with the use granted to the poor, is not fruitless to the owner, since it is meritorious for eternity and fitting for the profession of the poor; and it is judged the more useful to him the more it exchanges temporal things for eternal ones.",
  "note": "The Roman-law rule is Inst. 2.4.1. John XXII quoted this very passage back against the friars in 1322: the rule concerns things that survive their use, and an egg does not (Decr. Conditorem [5])."
 },
 {
  "pg": "1114",
  "titel": "The Roman Church takes the ownership",
  "orig": "Ad haec quum fratres ipsi nihil sibi in speciali acquirere, vel eorum ordini possint etiam in communi, et quum aliquid propter Deum ipsis offertur, conceditur vel donatur, ea, si secus non exprimat, offerentis, concedentis vel donantis verisimiliter credatur intentio, ut rem huiusmodi oblatam, concessam vel donatam perfecte concedat, donec auferat, a se abdicet, ac in alios transferre cupiat propter Deum, nec sit persona, in quam loco Dei congruentius huiusmodi rei dominium tranferat, quam sedes praefata vel persona Romani Pontificis Christi vicarii, qui pater est omnium et fratrum Minorum nihilominus specialis: ne talium rerum sub incerto videatur esse dominium, quum patri filius suo modo, servus domino, et monachus monasterio res sibi oblatas, concessas vel donatas acquirant: omnium utensilium et librorum, ac eorum mobilium praesentium et futurorum, quae et quorum usumfructum scilicet ordinibus vel fratribus ipsis licet habere, proprietatem et dominium, quod et felicis recordationis Innocentius Papa IV. praedecessor noster fecisse dignoscitur, in nos et Romanam ecclesiam plene et libere pertinere hac praesenti constitutione in perpetuum valitura sancimus.",
  "en": "Further, since the friars can acquire nothing individually for themselves, nor even in common for their order, and when something is offered, granted or given to them for God's sake, the intention of the one offering, granting or giving is, unless he expresses otherwise, to be believed to be that he grants the thing so offered, granted or given perfectly, renounces it until he takes it back, and wishes to transfer it to others for God's sake; and there is no person to whom he could more fittingly transfer the ownership of such a thing in God's place than the said see or the person of the Roman pontiff, the vicar of Christ, who is the father of all and no less especially of the Friars Minor: lest the ownership of such things seem to be uncertain, since a son acquires in his way for his father, a slave for his master and a monk for his monastery the things offered, granted or given to them: we ordain by this present constitution, valid for ever, that the property and ownership of all utensils and books, and of the movables present and future which, and whose usufruct, the orders or the friars may have, belong fully and freely to us and to the Roman Church, as our predecessor Pope Innocent IV of happy memory is known to have done.",
  "note": "'Usumfructum' here is Friedberg's text; the passage speaks throughout of the friars' use. Innocent IV had declared the Roman Church owner in Ordinem vestrum (1245). Forty-three years later John XXII renounced the ownership taken here, 'verbal, bare and enigmatic' (Decr. Conditorem [11])."
 },
 {
  "pg": "1115",
  "titel": "Money through a third hand",
  "orig": "Ceterum quum in eadem regula sit sub praecepti districtione prohibitum, ne fratres recipiant per se vel per alios denarios vel pecuniam ullo modo, idque fratres in perpetuum servare cupiant, et velut iniunctum necesse habeant adimplere, ne ipsorum puritas in huiusmodi observatione praecepti maculetur in aliquo, et ne fratrum conscientiae aliquibus aculeis stimulentur: articulum istum propter detrahentium morsus profundius, quam nostri praedecessores fecerint, assumentes, ac ipsum clarioribus determinationibus prosequentes, dicimus in primis, quod fratres ipsi a mutuis contrahendis abstineant, quum eis mutuum contrahere, ipsorum statu considerato, non liceat. Possint tamen ipsi pro satisfactione facienda, pro eorum necessitatibus, quae pro tempore occurrerint, (cessantibus eleemosynis, de quibus satisfieri commode tunc non posset,) citra cuiuslibet obligationis vinculum dicere, quod per eleemosynas et alios amicos fratrum ad solutionem huiusmodi faciendam intendant fideliter laborare. Quo casu procuretur a fratribus, quod ille, qui dabit eleemosynam, per se vel per alium, non nominandum ab ipsis, si fieri poterit, sed ab eo potius iuxta suum beneplacitum assumendum, huiusmodi satisfactionem faciat in totum vel in partem, prout sibi Dominus inspirabit. Si tamen ipse hoc nollet facere, vel non posset, vel quia recessus eius immineat, aut quia, quibus hoc velit committere, notitiam non habet fidelium personarum, seu quacunque alia occasione vel causa: declaramus et dicimus, quod in nullo regulae puritas infringitur, aut quomodolibet ipsius observantia maculatur, si fratres ipsi alicuius vel aliquorum sibi curent dare notitiam, vel aliquos seu aliquem nominare aut etiam praesentare, cui vel quibus, si eleemosynam facienti placuit, committi possit exsecutio praedictorum, ac ipsius habeatur assensus super subrogationibus infra scriptis, ita tamen, quod penes ipsum dantem dominio, proprietate, ac possessione ipsius pecuniae, cum libera potestate revocandi sibi pecuniam ipsam semper usque ad conversionem ipsius in deputatam, plene, libere ac integre remanentibus, in ipsa pecunia nihil omnino fratres iuris habeant, nec administrationem seu dispensationem, nec contra personam nominatam vel non nominatam ab eis, cuiuscunque conditionis exsistat, in iudicio vel extra actionem, persecutionem aut aliquod aliud ius intentent, qualitercunque persona praedicta in commissione huiusmodi se habeat.",
  "en": "Further, since in the same rule it is forbidden under a strict precept that the friars receive coins or money in any way, themselves or through others, and the friars wish to keep this for ever and hold it necessary to fulfil it as an injunction: lest their purity be stained in anything in the keeping of this precept, and lest the friars' consciences be pricked by any goads, we take up this article more deeply than our predecessors did, because of the bites of the detractors, and pursue it with clearer determinations. We say first that the friars must abstain from contracting loans, since, their state considered, it is not lawful for them to contract a loan. They may, however, in order to make satisfaction for their needs as they occur from time to time (when alms fail, from which satisfaction could not conveniently be made then), say, without the bond of any obligation, that they intend to work faithfully through alms and other friends of the friars to have such payment made. In which case the friars shall see to it that the one who gives the alms makes such satisfaction, in whole or in part, as the Lord inspires him, himself or through another, not named by them, if it can be done, but rather taken by him at his pleasure. If, however, he would not or could not do this, either because his departure is imminent, or because he does not know trustworthy persons to whom he would commit it, or for any other occasion or cause: we declare and say that the purity of the rule is in no way broken, nor its observance in any way stained, if the friars take care to make someone or some persons known to him, or to name or even present someone or some persons to whom, if it please the giver of the alms, the execution of the foregoing may be committed, and his assent is had to the substitutions written below; on condition, however, that the lordship, property and possession of that money remain fully, freely and wholly with the giver himself, with free power to recall the money to himself always until it is turned to its assigned purpose; that the friars have no right at all in that money, nor its administration or dispensation, nor bring any action, suit or other right, in court or out of it, against the person named or not named by them, of whatever condition, however that person conducts himself in the commission.",
  "note": "The 'spiritual friend' or agent (nuntius) who handled money for the friars became, by Martin IV's bull of 1283, a procurator acting in the name of the Roman Church. John XXII abolished those procurators in 1322 (Decr. Conditorem [12])."
 },
 {
  "pg": "1120–1121",
  "titel": "To be read in the schools, and not glossed",
  "orig": "Quum igitur ex praedictis et aliis, per nos cum multa maturitate discussis, regula ipsa licita, sancta, perfecta et observabilis, nec ulli patens discrimini evidenter appareat: illa et omnia supra scripta per nos statuta, ordinata, concessa, disposita, decreta, declarata etiam et suppleta, de apostolicae potestatis plenitudine approbamus, confirmamus et volumus exsistere perpetuae firmitatis, in virtute obedientiae districte praecipientes, quod haec constitutio sicut ceterae constitutiones vel decretales epistolae legatur in scholis. […] Itaque sub poena excommunicationis et privationis officii ac beneficii districte praecipimus, ut praesens constitutio, quum ipsam legi contigerit, sicut prolata est, sic fideliter exponatur ad literam, concordantiae, contrarietates seu diversae vel adversae opiniones a lectoribus seu expositoribus nullatenus inducantur. Super ipsa constitutione glossae non fiant, nisi forsan, per quas verbum vel verbi sensus, seu constructio, vel ipsa constructio quasi grammaticaliter ad literam vel intelligibilius exponatur. Nec intellectus ipsius per legentem depravetur in aliquo, seu distorqueatur ad aliud, quam litera ipsa sonat. […] Sed si quid penes aliquem in his ambiguitatis emerserit, ad culmen praedictae sedis apostolicae deducatur, ut ex auctoritate apostolica sua in hoc manifestetur intentio, cui soli concessum est in his statuta concedere et edita declarare. […] Nulli ergo omnino hominum liceat hanc paginam nostrae declarationis, ordinationis, concessionis, dispositionis, approbationis, confirmationis et constitutionis infringere, vel ei ausu temerario contraire. Si quis autem hoc attentare praesumpserit, indignationem omnipotentis Dei et beatorum Petri et Pauli Apostolorum eius se noverit incursurum. Datum Siriani XVIII. Kalend. Septembris, Pontificatus nostri anno secundo.",
  "en": "Since, then, from the foregoing and other things discussed by us with much deliberation, the rule itself plainly appears lawful, holy, perfect and observable, and open to no danger: we approve, confirm and will to be of perpetual force, from the fullness of apostolic power, it and all the things written above, ordained, granted, disposed, decreed, declared and supplied by us, strictly commanding in virtue of obedience that this constitution be read in the schools like the other constitutions or decretal letters. […] Therefore we strictly command, under pain of excommunication and deprivation of office and benefice, that when this present constitution comes to be read, it be expounded faithfully to the letter as it has been pronounced; that no concordances, contradictions, or differing or contrary opinions be brought in by the readers or expositors. Let no glosses be made on this constitution, except perhaps such as expound the word or the sense of the word, or the construction, or the construction itself as it were grammatically to the letter or more intelligibly. Nor let its meaning be corrupted in anything by a reader, or twisted to anything other than what the letter itself says. […] But if anything ambiguous in these matters arises with anyone, let it be brought to the summit of the said apostolic see, so that its intention may be made plain on this by its apostolic authority, to which alone it is granted in these matters to make statutes and to declare what has been issued. […] Let no man at all, then, infringe this page of our declaration, ordinance, grant, disposition, approval, confirmation and constitution, or rashly oppose it. If anyone should presume to attempt this, let him know that he will incur the indignation of almighty God and of his blessed apostles Peter and Paul. Given at Soriano on the eighteenth day before the Kalends of September, in the second year of our pontificate.",
  "note": "The ban on glossing is the one John XXII suspended in March 1322 (Decr. Nonnunquam [2]–[3]). The sentence reserving every doubt to the apostolic see, 'to which alone it is granted to make statutes and to declare what has been issued', is the one John XXII quoted in 1324 against the friars' claim that a pope may not revoke what his predecessor defined. Friedberg's text reads 'statuta concedere et edita declarare'; John XXII quotes the sentence in 1324 as 'statuta condere et condita declarare' (Quia quorundam, col. 1236, in a part not yet carried)."
 }
]

EXIVI = [
 {
  "pg": "1193",
  "titel": "The garden",
  "orig": "„Exivi de paradiso, dixi: rigabo hortum plantationum,“ ait ille coelestis agricola, qui vere fons sapientiae, verbum Dei, a Patre, in Patre manens, genitum ab aeterno novissime diebus istis, fabricante sancto Spiritu in utero virginis caro factum, exivit homo ad opus arduum redemptionis humani generis peragendum, exemplar se dando coelestis vitae, praebens hominibus semet ipsum. Verum quia plerumque mortalis vitae sollicitudinibus pressus homo mentis adspectum ab exemplaris huiusmodi intuitu divertebat: verus noster Salomon in solio militantis ecclesiae hortum voluptatis inter ceteros quendam fecit a procellosis mundi fluctibus elongatum, in quo quietius ac securius vacaretur contemplandis servandisque huiusmodi operibus exemplaris, in hunc mundum introivit ipse, ut rigaret ipsum foecundis aquis spiritualis gratiae et doctrinae. Hic hortus siquidem est fratrum Minorum sancta religio, quae muris regularis observantiae firmiter undique circumclusa, intra se solo contenta Deo, adornatur abunde novellis plantationibus filiorum. Ad hunc veniens dilectus Dei filius mortificantis poenitentiae myrrham metit cum aromatibus, quae suavitate mira universis odorem attrahentis sanctimoniae circumfundunt. Haec est illa coelestis vitae forma et regula, quam descripsit ille confessor Christi eximius sanctus Franciscus, ac servandam a suis filiis verbo docuit pariter et exemplo. […]",
  "en": "'I came out of paradise; I said: I will water the garden of my plants,' says that heavenly husbandman who is truly the fount of wisdom, the Word of God, born of the Father from eternity and abiding in the Father, who in these last days, made flesh by the working of the Holy Spirit in the womb of the Virgin, came out as man to accomplish the hard work of the redemption of the human race, giving himself as the pattern of heavenly life and offering himself to men. But since man, pressed for the most part by the cares of mortal life, turned the gaze of his mind away from the sight of that pattern, our true Solomon made in the throne of the Church militant, among others, a certain garden of delight, withdrawn from the stormy waves of the world, in which one might attend more quietly and securely to contemplating and keeping the works of that pattern; and he himself entered this world to water it with the fruitful waters of spiritual grace and teaching. This garden is the holy religion of the Friars Minor, which, firmly enclosed on every side by the walls of regular observance, content within itself with God alone, is richly adorned with new plantings of sons. Coming into it, the beloved Son of God reaps the myrrh of mortifying penance with the spices, which pour round all things, with wonderful sweetness, the fragrance of a holiness that draws. This is that form and rule of heavenly life which the outstanding confessor of Christ, Saint Francis, wrote, and taught his sons by word and example alike to keep. […]",
  "note": "Clement V at the Council of Vienne, promulgated 6 May 1312. The opening words are Ecclesiasticus 24:41–42 (Vulgate). The medieval summary printed before it: 'Some things in the chapter Exiit are declared, above all whether the Friars Minor are bound to observe everything the rule sets in the imperative mood; then many things are added to which the friars themselves are bound; and consequently, after nine excesses of theirs are discussed at length, the election of their minister is treated most clearly.' The 'nine excesses' are the Spirituals' complaints against the Community, given in the next excerpt."
 },
 {
  "pg": "1196–1197",
  "titel": "The Spirituals' complaint",
  "orig": "[…] Proinde quum vir sanctus, paupertatis praemissae in regulam modum exprimens, dixerit in eadem: „ Fratres nihil sibi approprient, nec domum, nec locum, nec aliquam rem, sed tanquam peregrini et advenae, in hoc saeculo in paupertate et humilitate Domino famulantes, vadant pro eleemosyna confidenter,\" sicque declaratum exstitit per nonnullos praedecessores nostros Romanos Pontifices, hanc expropriationem intelligi debere tam in speciali quam etiam in communi, propter quod et rerum omnium concessarum, oblatarum et donatarum fratribus, (quas et quarum usum, facti scilicet, ordini vel ipsis fratribus licet habere,) proprietatem et dominium in se et Romanam ecclesiam receperunt, dimisso ipsis fratribus in eis tantummodo usu facti simplicis: ad nostrum fuerunt deducta examen, quae in ordine fieri dicebantur, et videbantur praedicto voto et puritati ordinis repugnare, videlicet, ut ea prosequamur ex ipsis, quae remedio credimus indigere, quod se institui heredes non solum sustinent, sed procurant; item, quod reditus annuos recipiunt interdum in tam notabili quantitate, quod conventus habentes totaliter inde vivunt; item, quod, quum ipsorum negotia etiam pro rebus temporalibus in curiis agitantur, assistunt advocatis et procuratoribus, et ad instigandum eosdem se ibidem personaliter repraesentant; item, quod exsecutiones ultimarum suscipiunt voluntatum et gerunt, seque intromittunt quandoque de usurarum vel male ablatorum dispositionibus seu restitutionibus faciendis; item, quod alicubi non solum excessivos hortos, sed etiam vineas magnas habent, de quibus tam de oleribus quam de vino multum colligitur ad vendendum; item, quod temporibus messium vel vindemiarum sic copiose granum et vinum mendicando vel aliunde emendo colliguntur a fratribus, et in cellariis et granariis reconduntur, quod per anni residuum et absque eorum mendicatione possunt transigere vitam suam, item, quod ecclesias vel alia aedificia faciunt vel procurant fieri in quantitate et curiositate figurae et formae, ac sumptuositate notabiliter excessiva, sic, quod non videntur habitacula pauperum, sed magnatum. Paramenta etiam ecclesiastica in plerisque locis tam multa habent et tam notabiliter pretiosa, quod excedunt in his magnas ecclesias cathedrales. Equos insuper et arma eis oblata in funeribus recipiunt indistincte. Tamen communitas fratrum, et specialiter rectores ipsius ordinis asserebant, quod praedicta seu plura ex ipsis in ordine non fiebant, quod et, si qui reperiuntur rei in talibus, rigide puniuntur, nec non contra talia, ne fiant, sunt facta pluries ab antiquo statuta in ordine multum stricta. […]",
  "en": "[…] Therefore, since the holy man, expressing in the rule the manner of the said poverty, said in it: 'Let the friars appropriate nothing to themselves, neither house, nor place, nor anything; but as pilgrims and strangers in this world, serving the Lord in poverty and humility, let them go for alms confidently'; and since it was declared by several of our predecessors as Roman pontiffs that this renunciation of ownership must be understood both individually and in common, for which reason they took into their own ownership and that of the Roman Church the property and lordship of all things granted, offered and given to the friars (which, and whose use, namely of fact, the order or the friars may have), leaving to the friars in them only the use of simple fact: there were brought to our examination things said to be done in the order which seemed contrary to that vow and to the purity of the order. To take up, namely, those of them that we believe to need a remedy: that they not only allow themselves to be instituted heirs, but seek it; that they sometimes receive annual revenues in so notable a quantity that the convents that have them live wholly on them; that, when their business is conducted in the courts, even for temporal things, they assist the advocates and procurators, and present themselves there in person to urge them on; that they take up and carry out the execution of last wills, and sometimes meddle in the disposal or restitution of usury or ill-gotten gains; that in some places they have not only excessive gardens but also great vineyards, from which much is gathered for sale, both vegetables and wine; that at harvest and vintage so much grain and wine is collected by the friars, by begging or buying elsewhere, and stored in cellars and granaries, that they can pass the rest of the year without begging; that they build, or have built, churches or other buildings of a size, a curiosity of shape and form, and a costliness notably excessive, so that they seem not the dwellings of the poor but of magnates; they also have in many places church vestments so many and so notably precious that they exceed the great cathedral churches in this; and they receive without distinction horses and arms offered to them at funerals. The community of the friars, however, and especially the rulers of the order, asserted that these things, or most of them, were not done in the order, that if any were found guilty of such things they were severely punished, and that very strict statutes had long been made in the order against them. […]",
  "note": "The list is the Spirituals' indictment of the Community, argued before the pope at Vienne by Ubertino of Casale and others against the order's leaders. Clement V answered it point by point; the next excerpts give his answers on granaries and on 'poor use'."
 },
 {
  "pg": "1198",
  "titel": "Granaries and cellars",
  "orig": "[…] Rursus quum praedictus Sanctus tam in exemplis vitae quam verbis regulae ostenderit, se velle, quod fratres sui et filii, divinae providentiae innitentes, suos in Deum iacerent cogitatus, qui volucres coeli pascit, quae non congregant in horrea, nec seminant, nec metunt: non est verisimile, voluisse ipsum eos habere granaria vel cellaria, ubi quotidianis mendicationibus deberent sperare posse transigere vitam suam. Et idcirco non ex timore levi relaxare se debent ad congregationes et conservationes huiusmodi faciendas, sed tunc tantum, quum esset multum credibile ex iam expertis, quod non possent vitae necessaria aliter invenire. Hoc autem ministrorum et custodum simul et separatim in suis administrationibus et custodiis, cum guardiani et duorum de conventu loci discretorum sacerdotum et antiquorum in ordine fratrum consilio et assensu, duximus iudicio relinquendum, eorum super hoc specialiter conscientias onerantes. […]",
  "en": "[…] Again, since the said Saint showed, both by the examples of his life and by the words of the rule, that he wished his friars and sons, relying on divine providence, to cast their thoughts on God, who feeds the birds of the air, which do not gather into barns, nor sow, nor reap: it is not likely that he wished them to have granaries or cellars where they could hope to pass their lives by daily begging. And therefore they must not relax, out of light fear, into making such collections and stores, but only when it would be very credible, from what has already been experienced, that they could not otherwise find the necessities of life. This we have left to the judgement of the ministers and custodians, together and separately, in their provinces and custodies, with the advice and consent of the guardian and of two discreet priests of the house, of long standing in the order, specially burdening their consciences on this. […]",
  "note": "Matthew 6:26. In 1317 John XXII confirmed this rule and made the superiors' judgement binding on all friars (Decr. Exigit [4]). The Spirituals held that even so the Community stored far more than necessity allowed."
 },
 {
  "pg": "1198–1199",
  "titel": "Poor use",
  "orig": "Ex praemissis autem succrevit non parum scrupulosa quaestio inter fratres, videlicet: utrum ex suae professione regulae obligentur ad arctum et tenuem sive pauperem usum rerum; quibusdam ex ipsis credentibus et dicentibus, quod, sicut quoad dominium rerum habent ex voto abdicationem arctissimam, ita ipsis quoad usum arctitudo maxima et exilitas est indicta; aliis in contrarium asserentibus, quod ex professione sua ad nullum usum pauperem, qui non exprimatur in regula, obligantur, licet teneantur ad usum moderatum temperantiae, sicut et magis ex condecenti, quam ceteri Christiani. Volentes itaque conscientiarum praedictorum fratrum providere quieti, et his altercationibus finem dare, declarando dicimus, quod fratres Minores ex professione suae regulae specialiter obligantur ad arctos usus seu pauperes, qui in ipsorum regula continentur, et eo obligationis modo, sub quo continet seu ponit regula dictos usus. Dicere autem, sicut aliqui asserere perhibentur, quod haereticum sit, tenere usum pauperem includi vel non includi sub voto evangelicae paupertatis, praesumptuosum et temerarium iudicamus.",
  "en": "From the foregoing arose among the friars a question full of scruple, namely whether by the profession of their rule they are bound to a strict and meagre or poor use of things (arctum et tenuem sive pauperem usum rerum); some of them believing and saying that, just as with regard to the ownership of things they have by vow the strictest renunciation, so with regard to use the greatest strictness and meagreness is enjoined on them; others asserting on the contrary that by their profession they are bound to no poor use that is not expressed in the rule, although they are bound to a moderate use of temperance, as other Christians are, and more so, as befits them. Wishing therefore to provide for the peace of conscience of the said friars and to put an end to these quarrels, we say, declaring, that the Friars Minor are specially bound by the profession of their rule to the strict or poor uses (arctos usus seu pauperes) that are contained in their rule, and in the manner of obligation in which the rule contains or sets those uses. But to say, as some are reported to assert, that it is heretical to hold that poor use is, or is not, included under the vow of evangelical poverty, we judge presumptuous and rash.",
  "note": "The usus pauper controversy was the Spirituals' question, as the ownership question of 1321–24 was the pope's. Peter John Olivi (d. 1298) had taught that poor use belonged to the vow; his followers, the Spirituals and the Beguins of Provence, were the ones John XXII ordered to obey in 1317 (Decr. Exigit [1]) and the inquisitors burned from 1318. Clement V died in 1314; his compromise, forbidding either side to call the other heretical, did not survive his successor."
 }
]

SECTIONS = [
    {"id": "exiit", "zk": "Exiit", "titel": "Exiit qui seminat (14 August 1279)",
     "blurb": "Nicholas III's definition of Franciscan poverty, the text the whole dispute was about: renunciation of ownership 'not only individually but also in common' is the way of Christ; Christ's purse was condescension to the weak; the friars have the 'simple use of fact' while the Roman Church owns their goods; money only through a third hand; and no one may gloss the decretal. Excerpts.",
     "units": EXIIT},
    {"id": "exivi", "zk": "Exivi", "titel": "Exivi de paradiso (6 May 1312)",
     "blurb": "Clement V at the Council of Vienne between the Spirituals and the Community: the garden of the Friars Minor; the Spirituals' list of the Community's excesses, from legacies to granaries and horses taken at funerals; granaries only in real need; 'poor use' binds as far as the rule states it, and neither side may call the other heretical. Excerpts.",
     "units": EXIVI},
]
